--local doOnTickGenerateGameCDs_Delay = 0
--local doOnTickGenerateGameCDs_LastSquare = nil
--
----- Randomize a virgin game disc
--local function randomizeGameDisc(disc)
--	local itemModData = disc:getModData()
--	local game = ComputerMod.getRandomGame()
--	if game then
--		ComputerMod.setGameDiscData(disc, game)
--		print("Randomize new Game CD:")
--		print("Title: " .. tostring(game.title))
--		print("Date: " .. tostring(game.date))
--		print("Publisher: " .. tostring(game.publisher))
--		print("Genre: " .. tostring(game.genre))
--	end
--end
--
----- Find unset Game CD and randomize them
--local function doOnTickGenerateGameCDs()
--	local playerObj = getPlayer()
--	local playerInv = playerObj:getInventory()
--	local currentSquare = playerObj:getSquare()
--
--	if doOnTickGenerateGameCDs_Delay > 100 then
--		--print("Search inventory")
--		local inventoryItems = playerInv:FindAll("Computer.Disc_Game")
--		for index=0,inventoryItems:size()-1 do
--			local item = inventoryItems:get(index)
--			if item:getType() == "Disc_Game" then
--				if not ComputerMod.getGameDiscData(item) then
--					randomizeGameDisc(item)
--				end
--			end
--		end
--		doOnTickGenerateGameCDs_Delay = 0
--	end
--	doOnTickGenerateGameCDs_Delay = doOnTickGenerateGameCDs_Delay + 1
--
--	if doOnTickGenerateGameCDs_LastSquare ~= currentSquare then
--		--print("Search square")
--		local playerX = playerObj:getX()
--		local playerY = playerObj:getY()
--		local playerZ = playerObj:getZ()
--		for y=playerY-2,playerY+2 do
--			for x=playerX-2,playerX+2 do
--				local square = getCell():getGridSquare(x, y, playerZ)
--
--				if square == nil then return end
--
--				--- Search items on Ground
--				local worldObjects = square:getWorldObjects()
--				for index=0,worldObjects:size()-1 do
--					local object = worldObjects:get(index)
--					local item = object:getItem()
--
--					if item:getType() == "Disc_Game" then
--						if not ComputerMod.getGameDiscData(item) then
--							randomizeGameDisc(item)
--						end
--					end
--
--					if item:getContainer() then
--						local containerItems = item:getContainer():getItems()
--						for cindex=0,containerItems:size()-1 do
--							local citem = containerItems:get(cindex)
--							if citem:getType() == "Disc_Game" then
--								if not ComputerMod.getGameDiscData(citem) then
--									randomizeGameDisc(citem)
--								end
--							end
--						end
--					end
--				end
--
--				--- Search items in Containers
--				local objects = square:getObjects()
--				for index=0,objects:size()-1 do
--					local object = objects:get(index)
--					local container = object:getContainer()
--
--					if container and container:contains("Disc_Game") then
--						local containerItems = container:getItems()
--						if containerItems and containerItems:size() > 0 then
--							for cindex=0,containerItems:size()-1 do
--								local citem = containerItems:get(cindex)
--								if citem:getType() == "Disc_Game" then
--									if not ComputerMod.getGameDiscData(citem) then
--										randomizeGameDisc(citem)
--									end
--								end
--							end
--						end
--					end
--				end
--			end
--		end
--		doOnTickGenerateGameCDs_LastSquare = currentSquare
--	end
--end
--
--Events.OnTick.Add(doOnTickGenerateGameCDs)