---                 uniqueId,      title,       date,       publisher,      genre
ComputerMod.addGame("pz_b41", "Project Zomboid", "2013", "The Indie Stone", "Survival game", "pz")
ComputerMod.addGame("metal_gear", "Metal Gear", "1987", "Konami", "Stealth game", "metal_gear")
ComputerMod.addGame("metal_gear_2", "Metal Gear 2: Solid Snake", "1990", "Konami", "Stealth game", "metal_gear_2")
ComputerMod.addGame("snake_revenge", "Snake's Revenge", "1990", "Konami", "Stealth game", "snake_revenge")
ComputerMod.addGame("elite", "Elite", "1984", "Frontier Developments", "Space sim", "elite")
ComputerMod.addGame("donkey_kong", "Donkey Kong", "1981", "Nintendo", "Arcade", "donkey_kong")
ComputerMod.addGame("contra", "Contra", "1987", "Konami", "Run & Gun Shooter", "Contra")
ComputerMod.addGame("the_legend_of_zelda", "The Legend of Zelda", "1986", "Nintendo", "Adventure", "the_legend_of_zelda")
ComputerMod.addGame("final_fantasy", "Final Fantasy", "1986", "Square", "RPG", "final_fantasy")
ComputerMod.addGame("the_lost_vikings", "The Lost Vikings", "1992", " Blizzard Entertainment", "Arcade", "The_Lost_Vikings")
ComputerMod.addGame("tetris", "Tetris", "1984", "Alexey Pajitnov", "Puzzle", "Tetris")
ComputerMod.addGame("duke_nukem", "Duke Nukem", "1991", "Apogee Entertainment", "Platformer", "duke_nukem")
ComputerMod.addGame("doom", "Doom", "1993", "id Software", "FPS", "doom")
ComputerMod.addGame("star_wars_x_wing", "Star Wars: X-Wing", "1993", "Lucasarts", "Space", "star_wars_x_wing")
ComputerMod.addGame("lemmings", "Lemmings", "1991", "Psygnosis", "Puzzle", "lemmings")
ComputerMod.addGame("civilization", "Civilization", "1991", "MicroProse", "4X Strategy", "civilization")
ComputerMod.addGame("dune_2", "Dune II", "1992", "Virgin Games", "RTS", "dune_2")
ComputerMod.addGame("wolfenstein_3d", "Wolfenstein 3D", "1992", "Apogee Software", "FPS", "wolfenstein")
ComputerMod.addGame("skate_or_die", "Skate or Die!", "1987", "Electronic Arts", "Sports", "skate_or_die")
ComputerMod.addGame("simcity", "SimCity", "1989", "Maxis", "Simulation", "simcity")

