require("Computer/ComputerMod")

---                 uniqueId,      title,       date,       publisher,      genre
ComputerMod.addGame("minesweeper", "Minesweeper", "1990", "Microsoft Entertainment", "Puzzle")
ComputerMod.addGame("commander_keen", "Commander Keen in Invasion of the Vorticons", "1990", "Apogee Software", "Platformer")
ComputerMod.addGame("cosmic_commandos", "Cosmic Commandos", "1978", "Otaio", "Shoot 'em up")
ComputerMod.addGame("candy_cat_adventure", "Candy Cat Adventure!", "1991", "Beacon Games", "Platformer")
ComputerMod.addGame("king_quest_1", "King’s Quest I: Quest for the Crown", "1984", "Sierra Entertainment", "Adventure")
ComputerMod.addGame("myst", "Myst", "1993", "Broderbund", "Adventure")
ComputerMod.addGame("ultima_iv", "Ultima IV: Quest of the Avatar", "1985", "Origin Systems", "RPG")
ComputerMod.addGame("castle_of_the_winds", "Castle of the Winds", "1989", "SaadaSoft", "Roguelike")
ComputerMod.addGame("rogue", "Rogue", "1980", "Epyx", "Roguelike")
ComputerMod.addGame("nethack", "NetHack", "1987", "The NetHack DevTeam", "Roguelike")
ComputerMod.addGame("pac_man", "Pac-Man", "1980", "Namco", "Arcade")
ComputerMod.addGame("space_invaders", "Space Invaders", "1978", "Taito", "Arcade")
ComputerMod.addGame("where_in_the_world_is_carmen_sandiego", "Where in the World is Carmen Sandiego?", "1985", "Broderbund", "Educational")
ComputerMod.addGame("the_oregon_trail", "The Oregon Trail", "1985", "MECC", "Educational")
ComputerMod.addGame("pirates_gold", "Pirates! Gold", "1993", "MicroProse", "Adventure")
ComputerMod.addGame("prince_of_persia", "Prince of Persia", "1989", "Broderbund", "Platform")
ComputerMod.addGame("dragon_lair", "Dragon’s Lair", "1983", "Cinematronics", "Interactive Film")
ComputerMod.addGame("solitaire", "Solitaire", "1990", "Microsoft", "Card")
ComputerMod.addGame("earl_weaver_baseball", "Earl Weaver Baseball", "1987", "Electronic Arts", "Sports")
ComputerMod.addGame("the_bard_tale", "The Bard’s Tale", "1985", "Electronic Arts", "RPG")
ComputerMod.addGame("might_and_magic_5_darkside_of_xeen", "Might and Magic 5: Darkside of Xeen", "1993", "New World Computing", "RPG")
ComputerMod.addGame("starflight", "Starflight", "1986", "Electronic Arts", "Space")
ComputerMod.addGame("wasteland", "Wasteland", "1988", "Electronic Arts", "RPG")
ComputerMod.addGame("john_madden_football", "John Madden Football", "1989", "Electronic Arts", "Sports")
ComputerMod.addGame("populous", "Populous", "1989", "Electronic Arts", "God Game")
ComputerMod.addGame("missile_command", "Missile Command", "1980", "Atari, Inc.", "Shoot 'em up")
ComputerMod.addGame("batman_returns", "Batman Returns", "1992", "Konami", "Beat 'em up")
ComputerMod.addGame("star_control", "Star Control", "1990", "Accolade", "Shoot 'em up")
ComputerMod.addGame("star_control_2", "Star Control II", "1992", "Accolade", "Shoot 'em up")
ComputerMod.addGame("horror_zombies_from_the_crypt", "Horror Zombies from the Crypt", "1990", "U.S. Gold", "Platform")
ComputerMod.addGame("isle_of_the_dead", "Isle of the Dead", "1993", "Merit Software", "FPS")
