local GameAPI = require("ComputerMod/GameAPI");

GameAPI.Add("minesweeper", "Minesweeper", "1990", "Microsoft Entertainment", "Puzzle")
GameAPI.Add("commander_keen", "Commander Keen in Invasion of the Vorticons", "1990", "Apogee Software", "Platformer")
GameAPI.Add("cosmic_commandos", "Cosmic Commandos", "1978", "Otaio", "Shoot 'em up")
GameAPI.Add("candy_cat_adventure", "Candy Cat Adventure!", "1991", "Beacon Games", "Platformer")
GameAPI.Add("king_quest_1", "King’s Quest I: Quest for the Crown", "1984", "Sierra Entertainment", "Adventure")
GameAPI.Add("myst", "Myst", "1993", "Broderbund", "Adventure")
GameAPI.Add("ultima_iv", "Ultima IV: Quest of the Avatar", "1985", "Origin Systems", "RPG")
GameAPI.Add("castle_of_the_winds", "Castle of the Winds", "1989", "SaadaSoft", "Roguelike")
GameAPI.Add("rogue", "Rogue", "1980", "Epyx", "Roguelike")
GameAPI.Add("nethack", "NetHack", "1987", "The NetHack DevTeam", "Roguelike")
GameAPI.Add("pac_man", "Pac-Man", "1980", "Namco", "Arcade")
GameAPI.Add("space_invaders", "Space Invaders", "1978", "Taito", "Arcade")
GameAPI.Add("where_in_the_world_is_carmen_sandiego", "Where in the World is Carmen Sandiego?", "1985", "Broderbund", "Educational")
GameAPI.Add("the_oregon_trail", "The Oregon Trail", "1985", "MECC", "Educational")
GameAPI.Add("pirates_gold", "Pirates! Gold", "1993", "MicroProse", "Adventure")
GameAPI.Add("prince_of_persia", "Prince of Persia", "1989", "Broderbund", "Platform")
GameAPI.Add("dragon_lair", "Dragon’s Lair", "1983", "Cinematronics", "Interactive Film")
GameAPI.Add("solitaire", "Solitaire", "1990", "Microsoft", "Card")
GameAPI.Add("earl_weaver_baseball", "Earl Weaver Baseball", "1987", "Electronic Arts", "Sports")
GameAPI.Add("the_bard_tale", "The Bard’s Tale", "1985", "Electronic Arts", "RPG")
GameAPI.Add("might_and_magic_5_darkside_of_xeen", "Might and Magic 5: Darkside of Xeen", "1993", "New World Computing", "RPG")
GameAPI.Add("starflight", "Starflight", "1986", "Electronic Arts", "Space")
GameAPI.Add("wasteland", "Wasteland", "1988", "Electronic Arts", "RPG")
GameAPI.Add("john_madden_football", "John Madden Football", "1989", "Electronic Arts", "Sports")
GameAPI.Add("populous", "Populous", "1989", "Electronic Arts", "God Game")
GameAPI.Add("missile_command", "Missile Command", "1980", "Atari, Inc.", "Shoot 'em up")
GameAPI.Add("batman_returns", "Batman Returns", "1992", "Konami", "Beat 'em up")
GameAPI.Add("star_control", "Star Control", "1990", "Accolade", "Shoot 'em up")
GameAPI.Add("star_control_2", "Star Control II", "1992", "Accolade", "Shoot 'em up")
GameAPI.Add("horror_zombies_from_the_crypt", "Horror Zombies from the Crypt", "1990", "U.S. Gold", "Platform")
GameAPI.Add("isle_of_the_dead", "Isle of the Dead", "1993", "Merit Software", "FPS")
