--
--local ISPlayerDataObject_createInventoryInterface = ISPlayerDataObject.createInventoryInterface;
--function ISPlayerDataObject:createInventoryInterface(...)
--    local ret = ISPlayerDataObject_createInventoryInterface(self, ...);
--    self.computerMechanicsUI = ComputerHardwareManagement:new(argshere); --TODO: Set args
--    self.computerMechanicsUI:initialise();
--    self.computerMechanicsUI:setVisible(false);
--    self.computerMechanicsUI:setEnabled(false);
--    ISLayoutManager.RegisterWindow('computerMechanics'..self.id, ComputerHardwareManagement, self.computerMechanicsUI);
--    return ret;
--end
